<?xml version="1.0" encoding="utf-8"?><Database Name="TestingDatabase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=pixcilelab;Initial Catalog=TestingDatabase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TestingDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(1600)" CanBeNull="true" />
      <Column Name="AccountStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDelete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>